### ISSUE TITLE
cycles?

### ISSUE THREAD

**Issue by Kubanis** [Hirourk/HASPaintLayers#3]
Hello and thank you for an amazing plugin!
My only question for now i about Cycles support. 
Texture I am painting now with HAS nodes is invisible/transparent
when I switch for cycles. I haven't even foudn sny meantioning
about cycles in HAS wiki. Doesn't it suppose to work?
And if not - do you plan support?

**Comment by Hirourk** [comment]
Hey! I've never tested it on cycles, I thought there is no need to, because it should work. I'm going to fix this, but for now you can just specify UV channel in material settings.

Eevee allows having empty value, so it automatically takes default uvs and cycles don't.

**Comment by Kubanis** [comment]
> Hey! I've never tested it on cycles, I thought there is no need to, because it should work. I'm going to fix this, but for now you can just specify UV channel in material settings.
> 
> Eevee allows having empty value, so it automatically takes default uvs and cycles don't.

Thank you that was the thing I was looking for!
It is not obvious for first time user, you have to do this. 

Thank you for teh quick answer!

**Comment by Hirourk** [comment]
Fixed in latest release

**Comment by Kubanis** [comment]
> Fixed in latest release

Amazing! It works, thank you.
